//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.DataEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.DataEntities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 External relations attributes can not appear: {0} 的本地化字符串。
        /// </summary>
        internal static string ElementExistExternalRelation {
            get {
                return ResourceManager.GetString("ElementExistExternalRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not appear keyword: Parent  的本地化字符串。
        /// </summary>
        internal static string ElementExistParent {
            get {
                return ResourceManager.GetString("ElementExistParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not appear simple property: {0} 的本地化字符串。
        /// </summary>
        internal static string ElementExistSimpleProperty {
            get {
                return ResourceManager.GetString("ElementExistSimpleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity {0} {1} failed treatment on the expression, because {2} 的本地化字符串。
        /// </summary>
        internal static string ElementGetTargetError {
            get {
                return ResourceManager.GetString("ElementGetTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} is already a root entity can&apos;t access the Parent property. 的本地化字符串。
        /// </summary>
        internal static string ElementIsRootNotUseParent {
            get {
                return ResourceManager.GetString("ElementIsRootNotUseParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} is already a simple property, but then there are still next property retrieval. 的本地化字符串。
        /// </summary>
        internal static string GetTargetExistSimpleProperty {
            get {
                return ResourceManager.GetString("GetTargetExistSimpleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name can not be null or empty. 的本地化字符串。
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is {0} root entity does not exist. 的本地化字符串。
        /// </summary>
        internal static string NotFindElement {
            get {
                return ResourceManager.GetString("NotFindElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find the name of the entity {0} because {1}. 的本地化字符串。
        /// </summary>
        internal static string NotFindElementBecause {
            get {
                return ResourceManager.GetString("NotFindElementBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity {0} {1} does not name the property exist. 的本地化字符串。
        /// </summary>
        internal static string NotFindProperty {
            get {
                return ResourceManager.GetString("NotFindProperty", resourceCulture);
            }
        }
    }
}
